#!/bin/bash
API_URL="https://pokeapi.co/api/v2/pokemon/25/"
request=$(curl -w "\n%{http_code}" -X GET "$API_URL" -H "Content-Type: application/json")
status_code=$(echo "$request" | tail -n1)
body=$(echo "$request" | head -n -1)

if [ "$status_code" -eq 200 ]; then
    echo "Request was successful and saved to the data.json file"
    echo $body | jq  '.' > data.json
else
    echo $body | jq '.' >> errors.json
    echo "Request failed with status code $status_code"

fi


# This script fetches data for the Pokémon with ID 25 (Pikachu) from the PokeAPI
# and formats the output using jq for better readability.
# Ensure you have jq installed to parse the JSON response.
# You can install jq using your package manager, e.g., `sudo apt-get install jq` on Debian-based systems.